language: ruby
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.3.3
  - 2.3.4
  - 2.4.1
services:
  - postgresql
env:
  - DB_USERNAME=postgres
before_script: bundle exec rake db:create
script: bundle exec rspec spec
